import 'package:arcibo/util/constant/arcibo_color.dart';
import 'package:flutter/material.dart';

const lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: ARCIBOColor.brownBrand,
  onPrimary: ARCIBOColor.whiteBrand,
  primaryContainer: Color(0xFFFFDEAB),
  onPrimaryContainer: Color(0xFF341100),
  secondary: ARCIBOColor.yellowBrand,
  onSecondary: ARCIBOColor.whiteBrand,
  secondaryContainer: Color(0xFFFFDBCE),
  onSecondaryContainer: Color(0xFF370E00),
  tertiary: Color(0xFFFF701F),
  onTertiary: ARCIBOColor.whiteBrand,
  tertiaryContainer: Color(0xFFFFDEAB),
  onTertiaryContainer: Color(0xFF281900),
  error: Color(0xFFBA1A1A),
  onError: Color(0xFFFFFFFF),
  errorContainer: Color(0xFFFFDAD6),
  onErrorContainer: Color(0xFF410002),
  outline: Color(0xFF6F797A),
  background: Color(0xFFFFFBFF),
  onBackground: Color(0xFF311300),
  surface: Color(0xFFFFFBFF),
  onSurface: Color(0xFF311300),
  surfaceVariant: Color(0xFFF4DED5),
  onSurfaceVariant: Color(0xFF52443D),
  inverseSurface: Color(0xFF322F35),
  onInverseSurface: Color(0xFFF5EFF7),
  inversePrimary: Color(0xFFF35D08),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFF984717),
  outlineVariant: Color(0xFFBEC8CA),
  scrim: Color(0xFF000000),
);